import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Header */}
        <header className="bg-blue-600 text-white py-4 text-center">
          <h1 className="text-2xl font-bold">MY WEBSITE</h1>
        </header>
        {/* Main Content */}
        <main className="container mx-auto my-8 p-6 bg-white text-black shadow-lg rounded-2xl">
          {children}
        </main>
        {/* Footer */}
        <footer className="bg-blue-600 text-white text-center py-3 mt-10">
          <p>2026 My Website</p>
        </footer>
        
      </body>
    </html>
  );
}
